---
name: Test Brewfile
on:
  push:
    branches:
      - main

  # Run once a week (see https://crontab.guru)
  schedule:
    - cron: '0 0 * * 0'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      git_user:
        description: Username to associate with running this action
        required: true
        default: Zhendong Jiang
      git_email:
        description: Email to associate with running this action
        required: true
        default: xautjzd@gmail.com
      debug_enabled:
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: true
        default: "true"

jobs:
    test:
      name: Build and configure the Brewfile test environment
      runs-on: macos-latest
      steps:
        - name: Set up git repository
          uses: actions/checkout@v2

        - name: Set up Homebrew
          uses: Homebrew/actions/setup-homebrew@master

        - name: Test Brewfile
          run: brew bundle
